version: "2.7"

rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php worker.php"

metrics:
  address: app:8234

temporal:
    address: temporal:7233
    namespace: default
    activities:
        num_workers: 1
    metrics:
        driver: prometheus
        address: app:8233

logs:
  encoding: json
  mode: development
  channels:
    server:
      level: debug
    metrics:
      level: error
    temporal:
      level: error
